spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:


flyway:
  baselineOnMigrate: true
  url: jdbc:postgresql://localhost:5432/postgres
  user: postgres
  password:
  enabled: true
  locations: classpath:db/migration